name: CI and environments
'on':
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch: null
permissions:
  contents: read
  packages: write
  id-token: write
concurrency:
  group: ci-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    uses: anomaly51/general-1-argocd/.github/workflows/build-and-stage.yaml@main
    with:
      application: shisha-guid-frontend
      components: '[{"key":"image","build_args":"VITE_API_URL=/api/v1\nVITE_SSR_API_URL=http://shisha-guid-backend/api/v1\nVITE_PUBLIC_SITE_URL="}]'
