name: Build and deploy

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: shisha-frontend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: anomaly51/github-actions-toolkit/.github/workflows/harbor-argocd-app.yml@main
    with:
      app-name: shisha-frontend
      notification-title: Shishiguid Frontend
      image-repository: harbor.api-api-api.com/shisha/frontend
    secrets: inherit
